### ISSUE TITLE
handle weird shell naming cases?

### ISSUE THREAD

**Issue by mwilliammyers** [mwilliammyers/ansible-pure#1]
Ref. [tasks/main.yml:3](https://github.com/mkwmms/ansible-pure/blob/6649e6bc32507257b1b16afe2e58c630db2aa595/tasks/main.yml#L3)

``` yml
# TODO: handle weird shell naming cases?
# ie. 'bash-5.1' instead of 'bash'
- name: setup
  include_vars: "{{ ansible_user_shell | basename }}.yml"

#####=== install ===#####
…
```
